project_id = "egkxizoqslvcbksquiue"

[functions.analyze-product]
verify_jwt = false

[functions.product-question]
verify_jwt = false

[functions.fetch_geo_prices]
verify_jwt = false

[functions.translate-product]
verify_jwt = false

[functions.analyze-product-intent]
verify_jwt = false